replicaCount: 1

app:
  name: <app-name>                     # Change: application name (used for Deployment, Service, Route, etc.)

image:
  repository: <workload-image>         # Change: container image for workload
  tag: <tag>
  pullPolicy: IfNotPresent

exporterImage:
  repository: <exporter-image>         # Change: Prometheus exporter image
  tag: <tag>
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    http: <workload-port>              # Change: main application port
    metrics: <exporter-port>           # Change: exporter metrics port

namespace: <team-namespace>            # Change: target namespace for workload