apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginxapp
  namespace: {{ .Values.namespace }}
  labels:
    app: nginxapp
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: nginxapp
    weight: 100
  wildcardPolicy: None