apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ .Values.app.name }}
    weight: 100
  wildcardPolicy: None
