apiVersion: v1
kind: Service
metadata:
  name: nginxapp
  namespace: {{ .Values.namespace }}
  labels:
    app: nginxapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginxapp
  ports:
    - name: http
      port: {{ .Values.service.ports.http }}
      targetPort: {{ .Values.service.ports.http }}
    - name: metrics
      port: {{ .Values.service.ports.metrics }}
      targetPort: {{ .Values.service.ports.metrics }}