apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginxapp
  namespace: openshift-monitoring
  labels:
    app: nginxapp
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: nginxapp
  endpoints:
    - port: metrics
      interval: 30s
      scheme: http