apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.app.name }}
  namespace: openshift-monitoring
  labels:
    app: {{ .Values.app.name }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  endpoints:
    - port: metrics
      interval: 30s
      scheme: http